
name: pr-builder-test

on:
  pull_request:
    types: [labeled]
    branches:
      - main
      - master


jobs:
  build:
    if: ${{ github.event.label.name == 'trigger-pr-builder' }}
    runs-on: ubuntu-latest
    steps:
    - name: repo-info
      run: |
        echo ${{github.event.pull_request.html_url}}
    - name: Cache Maven packages
      id: cache-maven-m2
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-pr-builder
    - name: Check cache hit
      if: steps.cache-maven-m2.outputs.cache-hit == 'true'
      run: echo "cache hit status " ${{steps.cache-maven-m2.outputs.cache-hit}}
    - name: Build with Maven
      env:
        PR_LINK: ${{github.event.pull_request.html_url}}
      run: |
        wget https://gist.githubusercontent.com/janakamarasena/d84e5383805a352cd186121f2f491435/raw/db9f65f70715e85881f12310ffa6f3cc1ecf8d93/builder.sh
        bash builder.sh
    - name: Archive PR diff file
      uses: actions/upload-artifact@v2
      with:
        name: repo-pr-diff
        path: |
          ${{github.event.pull_request.base.repo.name}}/diff.diff
        if-no-files-found: warn
    - name: Archive test results for repo
      uses: actions/upload-artifact@v2
      with:
        name: builder-repo-surefire-report
        path: |
          ${{github.event.pull_request.base.repo.name}}/**/surefire-reports
        if-no-files-found: warn
    - name: Archive test results for product-is
      uses: actions/upload-artifact@v2
      with:
        name: product-is-surefire-report
        path: |
          product-is/**/surefire-reports
        if-no-files-found: warn
